### ISSUE TITLE
Wrong redirection after creating a new post

### ISSUE THREAD

**Issue by tomsihap** [28harishkumar/blog#1]
Hi,

First of all, thanks for the tutorial. It helps a lot.

After creating a user and writing a new blog post, it is redirected to http://localhost:8888/new-post which is wrong.
I've tried to edit config/app.php : url' => 'http://localhost:8888/larablog/public' 
but it still doesn't work.

Best regards,
Thomas

**Comment by FPGL** [comment]
Hi,

In `app/Http/Controllers/PostController.php`, try to replace in `function store()` & `function update()` :

```
return redirect(edit/' . $post->slug)->withMessage($message);
```

With 

```
return redirect($post->slug)->withMessage($message);
```

**Comment by 28harishkumar** [comment]
@FPGL I am redirecting to edit page of the post, not on view page.
@tomsihap I have checked the code again on my local server and it is working find without any change. Same code is in demo with different settings and postgresql database. But today I find that same problem is asked in the forum of my website. Please can you share more detail of the issue like title of your post and slug of that post in your database.
