### ISSUE TITLE
Setup database link is not working 

### ISSUE THREAD

**Issue by rjkhan** [28harishkumar/blog#11]
hi 
in your documentation, the step up database links not working... when i clicked on that link the domain is expire i guess

where i can find a solution to connect a database

thanks

**Comment by 28harishkumar** [comment]
Hi rjkhan,
As I was running out  of money, I could renew my server as well as domain last month. 
You can config database by using there references: 
https://github.com/28harishkumar/blog/blob/master/config/database.php
https://laravel.com/docs/5.6/database
