### ISSUE TITLE
Forgot Your Password / Reset Password not working

### ISSUE THREAD

**Issue by ghost** [28harishkumar/blog#7]
ERROR:
ErrorException in StreamBuffer.php line 95:
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

----my .env file-----
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=mygmail@gmail.com
MAIL_PASSWORD=mypassword

and mail.php
'from' => ['address' => 'mygmail@gmail.com', 'name' => 'mypassword'],

**Comment by 28harishkumar** [comment]
https://github.com/28harishkumar/laravel_blog
